import { init as initHelloTriagnle } from "./helloTriagnle";
import { init as initHelloTriagnleMSAA } from "./helloTriangleMSAA";
import { init as initRotatingCube } from "./rotatingCube";
import { init as initTwoCubes } from "./twoCubes";
import { init as initTexturedCube } from "./texturedCube";
import { init as initInstancedCube } from "./instancedCube";
import { init as initFractalCube } from "./fractalCube";
import { init as initComputeBoids } from "./computeBoids";
import { init as initAnimometer } from "./animometer";
import { init as initShadowMapping } from "./shadowMapping";
// initHelloTriagnle();
// initHelloTriagnleMSAA();
// initRotatingCube();
// initTwoCubes();
// initTexturedCube();
// initInstancedCube();
// initFractalCube();
// initComputeBoids();
// initAnimometer();
initShadowMapping();
